/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AchievementItem } from './achievement-item';


export interface AchievementsResponse { 
    unlocked: Array<AchievementItem>;
    all_possible: Array<AchievementItem>;
}

