/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AchievementItem { 
    module: string;
    key: string;
    title: string;
    description: string;
    icon: string;
    locked: boolean;
    unlocked_at?: string | null;
    progress_current: number;
    progress_target: number;
}

