/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HabitUpdate { 
    title?: string;
    frequency?: HabitUpdate.FrequencyEnum;
    target_per_week?: number;
}
export namespace HabitUpdate {
    export const FrequencyEnum = {
        Daily: 'daily',
        Weekly: 'weekly',
        Custom: 'custom'
    } as const;
    export type FrequencyEnum = typeof FrequencyEnum[keyof typeof FrequencyEnum];
}


