/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HabitToggle { 
    /**
     * Date to mark complete (defaults to today)
     */
    date?: string;
}

