/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HabitResponse { 
    readonly id?: number;
    title?: string;
    frequency?: string;
    target_per_week?: number;
    readonly created_at?: string;
    readonly updated_at?: string;
    readonly completions?: any | null;
    /**
     * Newly awarded achievement keys
     */
    readonly awarded?: Array<string>;
}

