/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JournalEntryResponse { 
    readonly id?: number;
    journal_id?: number;
    title?: string | null;
    content_json?: { [key: string]: any; };
    background?: string;
    font_family?: string;
    font_size?: number;
    entry_date?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
}

