/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JournalResponse { 
    readonly id?: number;
    title?: string;
    description?: string | null;
    cover_url?: string | null;
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Newly awarded achievement keys
     */
    readonly awarded?: Array<string>;
}

