/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JournalEntryCreate { 
    title?: string | null;
    content_json: object;
    background?: string;
    font_family?: string;
    font_size?: number;
    entry_date?: string;
}

