/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MoodCreate { 
    /**
     * The current mood
     */
    mood: string;
    /**
     * Optional note about the mood
     */
    note?: string | null;
}

