/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaginationMetadata { 
    total?: number;
    total_pages?: number;
    first_page?: number;
    last_page?: number;
    page?: number;
    previous_page?: number;
    next_page?: number;
}

