/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlannerEventResponse { 
    readonly id?: number;
    title?: string;
    description?: string | null;
    event_date?: string;
    start_time?: string | null;
    end_time?: string | null;
    reminder_minutes_before?: number | null;
    created_at?: string;
    updated_at?: string;
    /**
     * Newly awarded achievement keys
     */
    readonly awarded?: Array<string>;
}

