/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StreakSummary { 
    mood_current: number;
    mood_longest: number;
    habit_current: number;
    habit_longest: number;
}
