/**
 * Moody API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Streak { 
    module: string;
    current_streak: number;
    longest_streak: number;
    last_action_date?: string | null;
}

