"""init schema

Revision ID: 56d1630fc39f
Revises: 
Create Date: 2026-03-03 15:26:36.604939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d1630fc39f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_prompts_category'), ['category'], unique=False)

    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('achievement_key', sa.String(length=64), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_key', name='uq_achievement_user_key')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('target_per_week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habits_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_habits_user_title', ['user_id', 'title'], unique=False)

    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title', name='uq_journals_user_title')
    )
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_user_id'), ['user_id'], unique=False)

    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='one_mood_per_day')
    )
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moods_user_id'), ['user_id'], unique=False)

    op.create_table('planner_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planner_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planner_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_planner_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_planner_user_date', ['user_id', 'event_date'], unique=False)

    op.create_table('streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_action_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module', name='uq_streak_user_module')
    )
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaks_user_id'), ['user_id'], unique=False)

    op.create_table('user_notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('mood_reminder_time', sa.Time(), nullable=True),
    sa.Column('habit_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('habit_reminder_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notification_settings_user_id'), ['user_id'], unique=True)

    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'user_id', 'date', name='uq_habit_completion_per_user_day')
    )
    with op.batch_alter_table('habit_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_completions_habit_id'), ['habit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_completions_user_id'), ['user_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('background', sa.String(length=32), nullable=False),
    sa.Column('font_family', sa.String(length=64), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_journal_entries_user_journal_date', ['user_id', 'journal_id', 'entry_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_entries_user_journal_date')
        batch_op.drop_index(batch_op.f('ix_journal_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_journal_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('habit_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_completions_user_id'))
        batch_op.drop_index(batch_op.f('ix_habit_completions_habit_id'))

    op.drop_table('habit_completions')
    with op.batch_alter_table('user_notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_settings_user_id'))

    op.drop_table('user_notification_settings')
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streaks_user_id'))

    op.drop_table('streaks')
    with op.batch_alter_table('planner_events', schema=None) as batch_op:
        batch_op.drop_index('ix_planner_user_date')
        batch_op.drop_index(batch_op.f('ix_planner_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_planner_events_event_date'))

    op.drop_table('planner_events')
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moods_user_id'))

    op.drop_table('moods')
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_user_id'))

    op.drop_table('journals')
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index('ix_habits_user_title')
        batch_op.drop_index(batch_op.f('ix_habits_user_id'))

    op.drop_table('habits')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_user_id'))

    op.drop_table('achievements')
    op.drop_table('users')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))

    op.drop_table('token_blacklist')
    with op.batch_alter_table('journal_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_prompts_category'))

    op.drop_table('journal_prompts')
    # ### end Alembic commands ###
