"""initial schema

Revision ID: 7673d49fa25b
Revises: 
Create Date: 2026-03-01 11:09:41.733871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7673d49fa25b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moods_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('planner_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_expires_at'))
        batch_op.drop_constraint(batch_op.f('token_blacklist_jti_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    with op.batch_alter_table('user_notification_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_notification_settings_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_notification_settings_user_id'))
        batch_op.create_index(batch_op.f('ix_user_notification_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_settings_user_id'))
        batch_op.create_index(batch_op.f('ix_user_notification_settings_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('user_notification_settings_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('token_blacklist_jti_key'), ['jti'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_token_blacklist_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')  # type: ignore[arg-type]

    with op.batch_alter_table('planner_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')  # type: ignore[arg-type]

    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')  # type: ignore[arg-type]
        batch_op.drop_index(batch_op.f('ix_moods_user_id'))

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')  # type: ignore[arg-type]

    # ### end Alembic commands ###
